import { useState, useEffect, useRef } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Send, Download, Sparkles } from 'lucide-react';
import ResearchProgress from './components/ResearchProgress';
import Dashboard from './components/Dashboard';
import GraphView from './components/GraphView';

function App() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState('idle'); // idle, working, done
  const [logs, setLogs] = useState([]);
  const [result, setResult] = useState(null);
  const [pdfUrl, setPdfUrl] = useState(null);
  const ws = useRef(null);
  const scrollRef = useRef(null);

  const startResearch = (e) => {
    e.preventDefault();
    if (!query.trim()) return;

    setStatus('working');
    setLogs(["Initializing connection..."]);
    setResult(null);

    // Connect WS
    // Clean company name for URL (simple sanitize)
    const company = query.trim();
    ws.current = new WebSocket(`ws://localhost:8000/ws/research/${company}`);

    ws.current.onopen = () => setLogs(p => [...p, "Connected to Atlas Core."]);

    ws.current.onmessage = (event) => {
      const data = JSON.parse(event.data);
      if (data.type === "log") setLogs(prev => [...prev, data.content]);

      if (data.type === "result") {
        setResult(data.profile);
        setPdfUrl(data.pdf_url);
        setStatus('done');
        ws.current.close();
      }
    };
  };

  // Auto-scroll to bottom of chat
  useEffect(() => {
    scrollRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [status, logs, result]);

  return (
    <div className="bg-[#050505] min-h-screen text-white font-sans flex flex-col">

      {/* 1. TOP BAR */}
      <div className="h-14 border-b border-white/5 flex items-center px-6 justify-between bg-[#0a0a0a]/50 backdrop-blur sticky top-0 z-50">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-blue-400" />
          <span className="font-semibold text-sm tracking-wide">ATLAS <span className="text-gray-600 font-normal">/ DEEP RESEARCH</span></span>
        </div>
      </div>

      {/* 2. MAIN CONTENT AREA */}
      <div className="flex-1 overflow-y-auto p-4 md:p-8 relative">
        <div className="max-w-4xl mx-auto min-h-[500px] flex flex-col justify-end pb-24">

          <AnimatePresence mode="wait">
            {/* IDLE STATE */}
            {status === 'idle' && (
              <motion.div
                initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="text-center py-20 space-y-6"
              >
                <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-br from-white to-gray-600 bg-clip-text text-transparent">
                  What company are you analyzing?
                </h1>
                <p className="text-gray-400">
                  Atlas performs autonomous deep dives into corporate entities.
                </p>
              </motion.div>
            )}

            {/* WORKING STATE */}
            {status === 'working' && (
              <motion.div
                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                className="w-full"
              >
                <ResearchProgress logs={logs} />
              </motion.div>
            )}

            {/* RESULT STATE */}
            {status === 'done' && result && (
              <motion.div
                initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="space-y-8"
              >
                {/* Result Header */}
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-2xl font-bold">Research Report: {result.name}</h2>
                    <p className="text-gray-400 text-sm">Generated by Atlas Agent</p>
                  </div>
                  {pdfUrl && (
                    <a href={pdfUrl} download target="_blank" className="btn-primary flex items-center gap-2 text-sm py-2">
                      <Download className="w-4 h-4" /> Download JSON/PDF
                    </a>
                  )}
                </div>

                {/* Graph */}
                <div className="w-full">
                  <GraphView data={result} />
                </div>

                {/* Main Data Content */}
                <Dashboard data={result} />

              </motion.div>
            )}
          </AnimatePresence>

          {/* Invisible element to scroll to */}
          <div ref={scrollRef} />
        </div>
      </div>

      {/* 3. INPUT AREA (Fixed Bottom) */}
      <div className="p-6 fixed bottom-0 left-0 w-full bg-gradient-to-t from-[#050505] via-[#050505] to-transparent z-40">
        <div className="max-w-3xl mx-auto relative group">
          <form onSubmit={startResearch}>
            <input
              type="text"
              disabled={status === 'working'}
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={status === 'working' ? "Analysis in progress..." : "Ask Atlas to research a company..."}
              className="w-full bg-[#151515] border border-white/10 rounded-2xl py-4 pl-6 pr-14 text-white placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-500/50 shadow-2xl transition-all"
            />
            <button
              type="submit"
              disabled={status === 'working' || !query}
              className="absolute right-3 top-3 p-2 bg-white text-black rounded-xl hover:bg-gray-200 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <Send className="w-4 h-4" />
            </button>
          </form>
          <div className="text-center mt-3 text-xs text-gray-600">
            Atlas Agent can make mistakes. Please verify important corporate data.
          </div>
        </div>
      </div>

    </div>
  );
}

export default App;
